### post reception
POST https://www.jasontech.cf/wedding/reception?id=5 HTTP/1.1
content-type: application/json

{
    "name": "dsfjoisjefojorfj2o",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

### get reception
GET https://www.jasontech.cf/wedding/kh/reception?id=13 HTTP/1.1

### search reception
GET https://www.jasontech.cf/wedding/kh/search?name=謝昀叡 HTTP/1.1

### export
GET https://www.jasontech.cf/wedding/export HTTP/1.1

### checkIn
POST https://www.jasontech.cf/wedding/kh/checkIn HTTP/1.1
Content-Type: application/json

{
    "id": 1,
    "attendance" : 1
}

### allList in recTable
@location = kh
POST https://www.jasontech.cf/wedding/{{location}}/recStatus HTTP/1.1
